name: analog_sync
description: Conecta cadernos físicos com ferramentas digitais de produtividade.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  flutter_image_compress: ^2.2.0
  intl: ^0.19.0
  uuid: ^4.3.3
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
